name: Auto assign author
description: Auto assign the author to the pull request

runs:
  using: composite
  steps:
    - shell: bash
      if: github.event.pull_request.user.type == 'User'
      env:
        GH_TOKEN: ${{ github.token }}
        PR: ${{ github.event.pull_request.html_url }}
        AUTHOR: ${{ github.event.pull_request.user.login }}
        REPO: ${{ github.repository }}
      run: gh pr edit "$PR" --add-assignee "$AUTHOR" --repo "$REPO"
      